### ISSUE TITLE
cannot clone

### ISSUE THREAD

**Issue by metarsul** [millix/millix-wallet#12]
root@master:~# git clone --recurse-submodules https://github.com/millix/millix-wallet.git 
Cloning into 'millix-wallet'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 831 (delta 3), reused 9 (delta 2), pack-reused 819
Receiving objects: 100% (831/831), 1.21 MiB | 1.39 MiB/s, done.
Resolving deltas: 100% (441/441), done.
Submodule 'deps/millix-node' (git@github.com:millix/millix-node.git) registered for path 'deps/millix-node'
Cloning into '/root/millix-wallet/deps/millix-node'...
Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:millix/millix-node.git' into submodule path '/root/millix-wallet/deps/millix-node' failed
Failed to clone 'deps/millix-node'. Retry scheduled
Cloning into '/root/millix-wallet/deps/millix-node'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:millix/millix-node.git' into submodule path '/root/millix-wallet/deps/millix-node' failed
Failed to clone 'deps/millix-node' a second time, aborting
root@master:~#

**Comment by eriksson** [comment]
you have to configure and attach your ssh public key to your GitHub account.
please find more information here: https://docs.github.com/pt/free-pro-team@latest/github/authenticating-to-github/error-permission-denied-publickey
