### ISSUE TITLE
grunt build-core nw-gyp.js: not found

### ISSUE THREAD

**Issue by metarsul** [millix/millix-wallet#13]
node-gyp exists, but fails to continue during `grunt build-core`

## SYSTEM
uname -a
Linux master 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux

cat /proc/cpuinfo 
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 44.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

## ERROR:

Warning: Command failed: cd app && npm install && webpack --config webpack.prod.config.js
`/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: 5: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: ./node_modules/nw-gyp/bin/nw-gyp.js: not found`
node-gyp exited with code: 127
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: sudo apt-get install g++ build-essential
RHEL users please run: yum install gcc-c++ and yum groupinstall 'Development Tools'
Alpine users please run: sudo apk add python make g++
/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: 5: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: ./node_modules/nw-gyp/bin/nw-gyp.js: not found
node-gyp exited with code: 127
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: sudo apt-get install g++ build-essential
RHEL users please run: yum install gcc-c++ and yum groupinstall 'Development Tools'`
Alpine users please run: sudo apk add python make g++
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fibers@4.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-03T17_58_14_145Z-debug.log
 Use --force to continue.

##  APT:
`apt-get install g++ build-essential`
build-essential is already the newest version (12.6).
g++ is already the newest version (4:8.3.0-1+rpi2).

## node-gyp

root@master:~/millix-wallet# ls /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp
`/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp`

root@master:~/millix-wallet# ls /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp
`/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp`

root@master:~/millix-wallet# ls ./node_modules/nw-gyp/bin/nw-gyp.js
`./node_modules/nw-gyp/bin/nw-gyp.js`

**Comment by eriksson** [comment]
Looks like you are trying to build the wallet UI for an arm arch. The UI uses NW.js which I'm not sure if it supports the armv7 arch.
