### ISSUE TITLE
Cloning issue

### ISSUE THREAD

**Issue by xxglamisxx** [millix/millix-wallet#21]
After issuing "git clone --recurse-submodules https://github.com/millix/millix-wallet.git -b develop" I get the response: "fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:millix/millix-node.git' into submodule path '/home/pi/millix-wallet/deps/millix-node' failed
Failed to clone 'deps/millix-node'. Retry scheduled
Cloning into '/home/pi/millix-wallet/deps/millix-node'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:millix/millix-node.git' into submodule path '/home/pi/millix-wallet/deps/millix-node' failed
Failed to clone 'deps/millix-node' a second time, aborting"

**Comment by eriksson** [comment]
The git submodule was updated https://github.com/millix/millix-wallet/commit/a8d26e58200a056444abb60a9f346639b843a725 . please, try cloning the repo again?
