### ISSUE TITLE
v1.12.7 macOS Wallet incorrectly reports new version

### ISSUE THREAD

**Issue by rinchen** [millix/millix-wallet#53]
v.1.12.7 macOS wallet is reporting that an upgrade to v1.11.2 is available

## Expected Behavior

No update message

## Current Behavior

Reporting that an upgrade is available

## Steps to Reproduce

1. Launch unsync'd wallet

<img width="1304" alt="Screen Shot 2021-12-31 at 15 52 51 " src="https://user-images.githubusercontent.com/44416/147840658-b7893a3e-c3fa-46e8-8c17-88bbfbd489e8.png">

**Comment by eriksson** [comment]
@rinchen thanks for your feedback. this issue has been fixed. the next time you reload your wallet, it will not show the message.
